# تم تعطيل جميع التحذيرات والتحليلات لتنظيف قائمة PROBLEMS

analyzer:
  exclude:
    - "**/*.dart"  # تجاهل جميع ملفات Dart من التحليل
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

# لا توجد قواعد linter
